import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.3';
import { GoogleGenerativeAI } from "https://esm.sh/@google/generative-ai@0.21.0";

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders });
    }

    try {
        const { generation_id } = await req.json();

        const supabase = createClient(
            Deno.env.get('SUPABASE_URL') ?? '',
            Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
        );

        // 1. Fetch generation details
        const { data: generation, error: fetchError } = await supabase
            .from('generations')
            .select('*')
            .eq('id', generation_id)
            .single();

        if (fetchError || !generation) {
            throw new Error('Generation not found');
        }

        // 1.5 Fetch user profile to check plan
        const { data: profile } = await supabase
            .from('profiles')
            .select('plan_type')
            .eq('id', generation.user_id)
            .single();

        const isWatermarked = !profile || profile.plan_type === 'trial' || profile.plan_type === null;

        // 2. Update status to processing
        await supabase
            .from('generations')
            .update({ status: 'processing' })
            .eq('id', generation_id);

        // 3. Initialize Gemini
        const genAI = new GoogleGenerativeAI(Deno.env.get('GEMINI_API_KEY') ?? '');
        const model = genAI.getGenerativeModel({ model: "gemini-3-flash" }); // 2025年12月リリースの最新モデル：Gemini 3 Flash

        // 4. Prepare Image for Analysis (to generate better prompt for Imagen)
        const imageRes = await fetch(generation.original_url);
        const imageBlob = await imageRes.blob();
        const imageData = await imageBlob.arrayBuffer();

        const result = await model.generateContent([
            {
                inlineData: {
                    data: btoa(String.fromCharCode(...new Uint8Array(imageData))),
                    mimeType: "image/jpeg",
                },
            },
            "Analyze this room and provide a highly detailed description for virtual staging. Style: " + generation.style + ". Focus on furniture placement, lighting, and textures.",
        ]);

        const analysis = result.response.text();
        console.log('Room Analysis:', analysis);

        // 5. In a real production scenario, we would now call Imagen 3 on Vertex AI
        // using the analysis text and the original image.
        // For this implementation, we simulate the generation delay and use the result.

        await new Promise(resolve => setTimeout(resolve, 3000));

        // Let's use a high-quality interior placeholder for the demonstration
        // In reality, this would be the URL of the image generated by Imagen
        const placeholderImages: Record<string, string> = {
            'モダン': 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&q=80&w=1200',
            'ミニマル': 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=1200',
            'クラシック': 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=1200',
            'スカンジナビア': 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&q=80&w=1200',
            'インダストリアル': 'https://images.unsplash.com/photo-1505691938895-1758d7eaa511?auto=format&fit=crop&q=80&w=1200',
        };

        const generatedUrl = placeholderImages[generation.style] || placeholderImages['モダン'];

        // 6. Update Database with success
        const { error: updateError } = await supabase
            .from('generations')
            .update({
                status: 'completed',
                generated_url: generatedUrl,
                is_watermarked: isWatermarked,
                metadata: {
                    ...generation.metadata,
                    gemini_analysis: analysis,
                    watermarked_at: isWatermarked ? new Date().toISOString() : null
                }
            })
            .eq('id', generation_id);

        if (updateError) throw updateError;

        return new Response(JSON.stringify({ success: true, analysis }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });

    } catch (error) {
        console.error('Generation Error:', error);

        // Update status to failed
        const supabase = createClient(
            Deno.env.get('SUPABASE_URL') ?? '',
            Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
        );
        await supabase
            .from('generations')
            .update({ status: 'failed' })
            .eq('id', req.json()?.generation_id);

        return new Response(JSON.stringify({ error: error.message }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            status: 400,
        });
    }
});
